# Logo (Font Awesome Class)
fa_logo: fa-codepen

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: Hello word

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:
  # Support for LiveRe comments system.
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere_uid: MTAyMC8zMzAwNS85NTY3

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: 
facebook_url: 
weixin_url: dscdtc
dribble_url: 
github_url: https://github.com/dscdtc/
googleplus_url: 
behance_url: 
fivehundredpx_url: 
email_url: dscdtc@protonmail.com
rss_url: /atom.xml

# Footer About Text
footer_about: "&nbsp;&nbsp;&nbsp;&nbsp;The world ain’t all sunshine and rainbows. It's a very mean and nasty place and I don't care how tough you are, it will beat you to your knees and keep you there permanently if you let it. You, me or nobody, is gonna hit as hard as life. But it ain’t about how hard you hit.It's about how hard you can get hit and keep moving forward. How much you can take，and keep moving forward!!"

# Footer Copyright Line
footer_copyright: "Copyright ©2018 <a href=\"https://github.com/dscdtc\">dscdtc</a>. All right reserved"

# Fireworks
fireworks: true

# Daovoice Online contact
daovoiceid: 771b3406

# --------------------------------------------------------------
# background settings
# --------------------------------------------------------------
# add canvas-nest effect
# see detail from https://github.com/hustcc/canvas-nest.js
canvas_nest: true

# 百度主动推送
baidu_push: true
